### ISSUE TITLE
How to install this collection for use with Ansible Automation Platform 2.4 and ansible-navigator

### ISSUE THREAD

**Issue by smatterchew** [Commvault/ansiblev2#13]
## Tool versions

|Tool|Version|
|---|---|
|ansible-core|2.15.10|
|ansible-navigator|24.2.0|
|Ansible Automation Platform|2.4|

## Issue
When running a play that requires a collection, Ansible Automation Platform (AAP2) will read the `./collections/requirements.yml` and install the collections listed there and make them available to the container running the play.  

A typical `./collections/requirements.yml` looks like:
```yaml
collections:
  - ansible.utils
  - cyberark.pas
```

How do I list the `commvault.ansible` collection in this file to get AAP2 to install it at runtime so my roles can use it?

Thank you.

**Comment by kevinjojeejoseph** [comment]
Hi @smatterchew 
You can now download using Ansible Galaxy
``ansible-galaxy collection install commvault.ansible``
