### ISSUE TITLE
default values do not seem to be considered

### ISSUE THREAD

**Issue by github-media-support** [Commvault/ansiblev2#14]
Hi! While working on the case, I found that for 
commvault.ansible.file_servers.backup
commvault.ansible.file_servers.restore
agent-type has to be provided, does no default to "file system" (not ie. "linux file system")
Additionally, if we do not provide backup_type, backupset, subclient, we'll see the errors thrown similar to the one shown abelow:
![obraz](https://github.com/Commvault/ansiblev2/assets/40215871/5adf0435-5fc1-4173-b5f3-b85d1ab89595)

**Comment by kevinjojeejoseph** [comment]
Can you please provide the full traceback here for the error you are seeing and the input YAML? This error seems to be coming from the SDK level.
As mentioned in the [docs](https://github.com/Commvault/ansiblev2?tab=readme-ov-file#commvaultansiblefile_serversbackup-), Linux File System is not a default but a separate value you will need to pass.
![image](https://github.com/Commvault/ansiblev2/assets/82494965/fae97105-f787-4743-bc04-dd6baf0b3ec3)
Please run the above commands with the relevant inputs and let us know what the error actually is.
Please refer [this file](https://github.com/Commvault/ansiblev2/blob/a5a619a264c02210fa6d2e32b959845b5d5623f1/plugins/modules/file_servers/backup.py#L144) to know how the backup is done with the SDK object.
