### ISSUE TITLE
Use ansible-galaxy to install collection

### ISSUE THREAD

**Issue by sfarheen27** [Commvault/ansiblev2#3]
To use the Commvault/ansiblev2 repository, the readme says to manually "Clone this repository in the given location <Default Ansible Collection Location>/ansible_collections/commvault/ and rename the repo folder from ansiblev2 to ansible." Since there is a galaxy.yml and a MANIFEST.json is it possible to use ansible-galaxy to install this collection instead? 

When I tried using the command:
`ansible-galaxy collection install git+https://github.com/Commvault/ansiblev2.git`

I got this error: 
```
ERROR! Collection requirement at '' has both a MANIFEST.json file and a galaxy.yml.
The requirement must either be an installed collection directory or a source collection directory, not both.
```

Looks like there should only be one file of  either the MANIFEST.json or a galaxy.yml

**Comment by kevinjojeejoseph** [comment]
Hi @sfarheen27,
For now the recommended approach is to use the steps in the [Folder Structure](https://github.com/Commvault/ansiblev2#folder) part of the readme which talks about cloning in the default ansible collection location
Please do the same
